project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "WANG SIYUAN"
  site-url: https://big-tank.github.io/wsy.github.io/
  favicon: misc/info/wsy.png
  repo-url: https://github.com/big-tank/wsy.github.io
  repo-actions: [edit, issue]
  
  page-footer: 
    left: "&copy; Copyright 2025, Siyuan Wang"
    right: 
      - icon: github
        href: https://github.com/big-tank/wsy.github.io

  navbar: 
    background: "#A9CCE3"
    search: true
    right: 
      - text: "Projects"
        href: projects/projects.qmd
      
      - text: "Publications"
        href: Publication/Publication.qmd
        
     # - text: "R packages"
     #   href: rpkg/rpkg.qmd
           
      - text: "Talks"
        href: talks/talks.qmd

      - text: "Blog/notes"
        href: blog/blog.qmd
        
      - text: "About me"
        href: about_me.qmd
        
      - text: "CV"
        href: misc/info/CV-WSY.pdf


format:
  html:
    theme: styles.scss


